services:
  apache:
    image: httpd:2.4
    container_name: apache-htaccess-test
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs:ro
      - ./apache.conf:/usr/local/apache2/conf/extra/httpd-local.conf:ro
    # Use /bin/sh for max compatibility (Alpine + Debian)
    command: >
      /bin/sh -lc '
        # enable mod_rewrite if commented
        if grep -q "^[#]*LoadModule rewrite_module" /usr/local/apache2/conf/httpd.conf; then
          sed -i "s/^#\s*LoadModule\s\+rewrite_module/LoadModule rewrite_module/" /usr/local/apache2/conf/httpd.conf
        fi
        # include our override that allows .htaccess
        echo "Include conf/extra/httpd-local.conf" >> /usr/local/apache2/conf/httpd.conf
        # start httpd explicitly by absolute path
        exec /usr/local/apache2/bin/httpd -DFOREGROUND
      '
