name: FOOPS!

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (leave empty to use current ref)"
        required: false
        default: "testo"
      onto_uri:
        description: "ONTO_URI"
        required: false
        default: "https://micheldumontier.github.io/testo/versions/0.0.1/testo.ttl"
jobs:
  foops:
    runs-on: ubuntu-latest
    env:
      GIST_ID: ${{ vars.GIST_ID }}
      DOCS_DIR: docs
      VERSION_DIR: versions
    
    steps:
      - name: Call FOOPS! API
        id: foops
        run: |
          ONTO_URI = ${{ inputs.onto_uri }}
          curl -X POST "https://foops.linkeddata.es/assessOntology" \
              -H  "accept: application/json" \
              -H "Content-Type: application/json" \
              -d "{  \"ontologyUri\": \"$ONTO_URI\"}" \
              -o foops-results.json

      - name: Upload foops results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: foops-results
          path: foops-results.json
          
      - name: Process FOOPS! results
        run: |
          python3 - << 'PY'
          import json, pathlib, os
          total_score = 0
          with open('foops-results.json') as f:
              data = json.load(f)
              tot_checks = len(data["checks"])
              passed_checks = 0
              for check in data["checks"]:
                  pas=check["total_passed_tests"]
                  tot=check["total_tests_run"]
              
                  check_score = pas / tot
                  total_score += check_score
                  
              overall_score = total_score / tot_checks * 100
              label = f"{overall_score:.1f}% ({total_score}/{tot_checks} tests)"
              with open(os.environ["GITHUB_ENV"], "a") as f:
                f.write(f"FOOPS_SCORE={label}\n")  
          PY
          
      - name: Badge — FOOPS
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: ontology-ci-foops-${{ env.SAFE_BRANCH }}.json
          label: FOOPS!
          message: ${{ env.FOOPS_SCORE }}
          color: ${{ steps.foops.outcome == 'success' && 'brightgreen' || steps.foops.outcome == 'cancelled' && 'yellow' || 'red' }}
